### ISSUE TITLE
Greek symbols not displayed in PNG

### ISSUE THREAD

**Issue by flying-sheep** [s-u/Cairo#25] opened 2020-01-25 12:39 UTC
When executing the following, I only see “, 1” in the resulting PNG.

```r
tf <- tempfile(fileext = '.png')
Cairo::CairoFonts('Noto Sans')
Cairo::Cairo(200, 200, tf, 'png', units = 'px', bg = 'white')
plot.new()
plot.window(0:1, 0:1)
text(.5, .5, labels = expression(list(rho, 1)))
dev.off()
```

**Comment by bersbersbers** [comment] 2021-07-27 11:00
Same here. The crazy thing is that replacing both `Cairo::` calls by the simple `grDevices::png(type = "cairo", filename = tf)` works fine.

**Comment by s-u** [comment] 2021-07-27 21:56
@flying-sheep this works fine for me, so I suspect you'll have to provide more details as this will be specific to your system and fonts available. Most importantly your system has to have the appropriate Symbol font (see `?CairoFonts`). Since Cairo 1.5-13 and R 4.0.0 you can also use Unicode fonts via `usePUA=FALSE` which helps on systems that don't have symbol fonts with PUA Adobe encoding, but do have fonts with the necessary symbols in the Unicode plane.

**Comment by bersbersbers** [comment] 2021-07-28 05:36
I am on OpenSUSE LEAP 15.2, R 4.1.0, Cairo package from CRAN (1.5-12.2):

```
> Cairo::CairoFont(usePUA = FALSE)
Error: 'CairoFont' is not an exported object from 'namespace:Cairo'
> Cairo::CairoFonts(usePUA = FALSE)
Error in Cairo::CairoFonts(usePUA = FALSE) : 
  unused argument (usePUA = FALSE)
```

The `NEWS` says that `CairoFont(usePUA=FALSE)` (missing an `s`?) should work from 1.5-13, so I guess this is somewhat expected. However, with 1.5-13 from RForge, it does not work, either:

```
tf <- 'x.png'
Cairo::CairoFonts(usePUA = FALSE)
Cairo::Cairo(200, 200, tf, 'png', units = 'px', bg = 'white')
plot.new()
plot.window(0:1, 0:1)
text(.5, .5, labels = expression(list(rho, 1)))
dev.off()
```

My fonts:
```
[07:28:09] ~$ fc-list | grep Symbol
/usr/share/fonts/truetype/Adobe-Symbol-Regular.otb: Adobe Symbol:style=Medium
```

By the way, 
```
install.packages("Cairo", repo="https://RForge.net")
```
is missing another `s`:
```
Warning message:
In install.packages("Cairo", repo = "https://RForge.net") :
  partial argument match of 'repo' to 'repos'
```

**Comment by s-u** [comment] 2022-09-21 00:34
I tried to reproduce this using Docker (`opensuse/leap`), and as far as I can tell the problem is that OpenSUSE lacks fonts with symbol support. The font mentioned above is no longer part of the distribution, and the fonts available on OpenSUSE ("Luxi" is all that `fc` will match for me) don't have symbols so the above is expected.

I'm not familiar enough with OpenSUSE to find a package that provides usable fonts for this (it's been over two decades since I last used SuSE ;)), but the closest to cross-platform compatibility I can think of is "Arial" which is known to have the symbol plane, so this works for me on OpenSUSE:
```r
Cairo::CairoFonts(usePUA = FALSE, symbol="Arial")
```
(after `zypper install fetchmsttfonts` to install the Arial font file)

I'll close this for now - as far as I can tell symbols work if Cairo can be provided with a font that supports them.

**Closed by s-u** 2022-09-21 00:34 UTC
