### ISSUE TITLE
Current R 4.3.0 Install on Mac

### ISSUE THREAD

**Issue by iwelch** [s-u/Cairo#40] opened 2023-04-24 22:36 UTC
just had to reinstall, because I had to upgrade R to 4.3.0.  this time,

```
xlib-backend.c:34:10: fatal error: 'X11/Intrinsic.h' file not found
#include <X11/Intrinsic.h>      /*->    Xlib.h  Xutil.h Xresource.h .. */
         ^~~~~~~~~~~~~~~~~
1 error generated.
make: *** [xlib-backend.o] Error 1
ERROR: compilation failed for package ‘Cairo’
```

my own XQuartz probably came courtesy via `brew install --cask xquartz` many years ago, because brew tells me XQuartz is already installed.  XQuartz is installed at /Applications/Utilities/ and updated to XQuartz 2.8.5 (xorg-server 21.1.6).  A little search on my file system tells me

```
./System/Volumes/Data/opt/X11/include/X11/IntrinsicP.h
./System/Volumes/Data/opt/X11/include/X11/Intrinsic.h
./System/Volumes/Data/opt/X11/include/X11/IntrinsicI.h
```

One of the include libraries indeed has an X11, but this one only contains

```
ls /opt/homebrew/include/X11 
DECkeysym.h@  XF86keysym.h@ Xatom.h@      Xfuncproto.h@ Xlibint.h@    Xosdefs.h@    Xresource.h@  Xwinsock.h@   fonts@
HPkeysym.h@   XKBlib.h@     Xauth.h@      Xfuncs.h@     Xlocale.h@    Xpoll.h@      Xthreads.h@   ap_keysym.h@  keysym.h@
ImUtil.h@     XWDFile.h@    Xcms.h@       Xlib-xcb.h@   Xmd.h@        Xproto.h@     Xutil.h@      cursorfont.h@ keysymdef.h@
Sunkeysym.h@  Xalloca.h@    Xdefs.h@      Xlib.h@       Xos.h@        Xprotostr.h@  Xw32defs.h@   dri@
X.h@          Xarch.h@      Xdmcp.h@      XlibConf.h@   Xos_r.h@      Xregion.h@    Xwindows.h@   extensions/
```

with the XQuartz includes not found, could you either update the library search list or tell the user in an error what [s]he should do?

PS: my own nasty fix was `sudo ln -s /System/Volumes/Data/opt/X11/include/X11 /opt/homebrew/Cellar/cairo/1.16.0_5/include/cairo/` during installation and then removing it.

regards,

/iaw

**Comment by s-u** [comment] 2023-04-25 00:40
Please use latest version, I believe this is a duplicate of closed #39

**Closed by s-u** 2023-04-25 00:40 UTC
